FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
    python3-pip \
    && pip3 install --upgrade pip

ENV LANG=en_US.utf8 \
    PYTHONIOENCODING=UTF-8

WORKDIR /app

COPY requirements.txt /app
RUN cd /app && \
    pip3 install -r requirements.txt

COPY src /app/src

WORKDIR /app/src

CMD python3 main.py
